version: '3.1'

services:
  db:  
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rahasia
      - MYSQL_DATABASE=bahanpokok
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80

  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./pokok-api:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
